name: Update Image

on:
  push:
    branches:
      - main  # 僅在 main 分支觸發
  workflow_dispatch:  # 手動觸發
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build server images
      run: |
        docker build --pull --no-cache -f dockerfile.django -t tsukisama9292/server:django-rolling .
        docker build --pull --no-cache -f dockerfile.nginx -t tsukisama9292/server:nginx-rolling .
        docker build --pull --no-cache -f dockerfile.redis -t tsukisama9292/server:redis-rolling .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push tsukisama9292/server:django-rolling
        docker push tsukisama9292/server:nginx-rolling
        docker push tsukisama9292/server:redis-rolling
    

  # pull-image:
  #   runs-on: self-hosted
  #   needs: build
  #   if: success()
  #   steps:
  #   - name: Pull the Docker image
  #     run: |
  #       docker pull tsukisama9292/server:django-rolling
  #       docker pull tsukisama9292/server:nginx-rolling
  #       docker pull tsukisama9292/server:redis-rolling